# Generated by Django 3.0.5 on 2020-05-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='locationid',
            field=models.ForeignKey(db_column='locationID', on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='modelnumber',
            field=models.ForeignKey(db_column='modelNumber', on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standardid',
            field=models.ForeignKey(db_column='standardID', on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='clientid',
            field=models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='backend.ClientName'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='modelnumber',
            field=models.OneToOneField(db_column='modelNumber', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.Product'),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='test_sequence_sequenceid',
            field=models.ForeignKey(db_column='Test Sequence_sequenceID', on_delete=django.db.models.deletion.CASCADE, to='backend.TestSequence'),
        ),
        migrations.AlterField(
            model_name='service',
            name='standardid',
            field=models.ForeignKey(db_column='standardID', on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clientid',
            field=models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='backend.ClientName'),
        ),
    ]
